/*

Experiment no :6


Implement a program to handle Arithmetic exception, Array Index
Out of Bounds. The user enters two numbers Num1 and Num2. The
division of Num1 and Num2 is displayed. If Num1 and Num2 are
not integers, the program would throw a Number Format
Exception. If Num2 were zero, the program would throw an
Arithmetic Exception. Display the exception.

*/
program :

import java.util.*;
class NumberException
{
    public static void main(String args[])
    {
        Scanner scr=new Scanner(System.in);
        int num1,num2,q;
        try
        {
            System.out.println("\nEnter the value of first integer : ");
            num1=Integer.parseInt(scr.next());
            System.out.println("\nEnter the value of second integer : ");
            num2=Integer.parseInt(scr.next());
            q=num1/num2;
            System.out.println("\nQuotient is : "+q);
        }
        catch(NumberFormatException e)
        {
            System.out.println(e);
        }
        catch(ArithmeticException e)
        {
            System.out.println(e);
        }
    }
}

Output :
/*
Enter the value of first integer : 
16

Enter the value of second integer : 
4

Quotient is : 4